[game]
hostname = "String Theory Server"
desc = "wtf? No rp??? Only fun?!"
map_pool = "ST14DefaultMapPool"
maxplayers = 25
soft_max_players = 20
map_rotation = true
peaceful_end = false
defaultpreset = "greenshift"
fallbackenabled = false
fallbackpreset = "greenshift"
role_timers = false
tabletop_place = true

[console]
login_host_user = "Welldzhik"

[atmos]
space_wind = true

[biomass]
easy_mode = false

[rules]
time = 10.0

[whitelist]
enabled = false

[ic]
flavor_text = true
punctuation = true

[shuttle]
auto_call_time = 0

[hub]
advertise = false
tags = "lang:ru,rp:low,region:eu_e"

[netres]
limit = 20

[status]
enable = true

[ooc]
enable_during_round = true

[looc]
enabled_dead = true
enabled_crit = true

[mood]
enabled = false
